[package]
name = "raven"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
speedy ={ version = "0.8.7" }
tokio = { version = "1.37.0", features = ["full"] }
toml = "0.8.12"
